from dataclasses import dataclass
from pathlib import Path

from backend.app.services.architecture_explanation import (
    ArchitectureExplanation,
    ArchitectureExplanationError,
    ArchitectureExplanationService,
)
from backend.app.services.repository_summary import RepositorySummaryError

MAX_LIST_ITEMS = 8


class ArchitectureDocsError(Exception):
    """Raised when architecture documentation cannot continue."""


@dataclass(frozen=True)
class ArchitectureDocSection:
    """One generated architecture documentation section."""

    heading: str
    content: str


@dataclass(frozen=True)
class ArchitectureDocStats:
    """Measurable output statistics for generated architecture documentation."""

    section_count: int
    word_count: int
    component_count: int
    evidence_path_count: int
    confidence: float


@dataclass(frozen=True)
class GeneratedArchitectureDoc:
    """Architecture documentation generated from repository intelligence."""

    repository_path: str
    title: str
    focus: str | None
    markdown: str
    sections: tuple[ArchitectureDocSection, ...]
    evidence_paths: tuple[str, ...]
    stats: ArchitectureDocStats


class ArchitectureDocsService:
    """Generates Markdown architecture documentation from grounded explanations."""

    def __init__(self, architecture_service: ArchitectureExplanationService) -> None:
        self.architecture_service = architecture_service

    def generate(self, repository_path: Path, focus: str | None = None) -> GeneratedArchitectureDoc:
        """Generate architecture documentation for a repository path."""
        try:
            explanation = self.architecture_service.explain(repository_path, focus=focus)
        except (RepositorySummaryError, ArchitectureExplanationError):
            raise
        except Exception as error:
            raise ArchitectureDocsError(str(error)) from error

        title = self._title(Path(explanation.repository_path), explanation.focus)
        sections = (
            ArchitectureDocSection("Overview", explanation.overview),
            ArchitectureDocSection("Core Components", self._components(explanation)),
            ArchitectureDocSection("Dependency Flow", self._list(explanation.dependency_flow)),
            ArchitectureDocSection("Call Flow", self._list(explanation.call_flow)),
            ArchitectureDocSection(
                "Architecture Observations", self._list(explanation.observations)
            ),
            ArchitectureDocSection("Evidence", self._evidence(explanation)),
            ArchitectureDocSection("Generated By Forge AI", self._generation_note(explanation)),
        )
        markdown = self._markdown(title, sections)
        return GeneratedArchitectureDoc(
            repository_path=explanation.repository_path,
            title=title,
            focus=explanation.focus,
            markdown=markdown,
            sections=sections,
            evidence_paths=explanation.evidence_paths,
            stats=ArchitectureDocStats(
                section_count=len(sections),
                word_count=len(markdown.split()),
                component_count=len(explanation.components),
                evidence_path_count=len(explanation.evidence_paths),
                confidence=explanation.confidence,
            ),
        )

    def _title(self, root: Path, focus: str | None) -> str:
        name = root.name or "Repository"
        return f"{name} Architecture: {focus}" if focus else f"{name} Architecture"

    def _components(self, explanation: ArchitectureExplanation) -> str:
        if not explanation.components:
            return "No architecture components were identified from the repository summary."
        lines: list[str] = []
        for component in explanation.components[:MAX_LIST_ITEMS]:
            lines.append(f"- `{component.path}`: {component.role}")
            lines.extend(f"  - Evidence: {item}" for item in component.evidence[:3])
        return "\n".join(lines)

    def _list(self, items: tuple[str, ...]) -> str:
        if not items:
            return "No signals were available."
        return "\n".join(f"- {item}" for item in items[:MAX_LIST_ITEMS])

    def _evidence(self, explanation: ArchitectureExplanation) -> str:
        if not explanation.evidence_paths:
            return "No evidence paths were available."
        return "\n".join(f"- `{path}`" for path in explanation.evidence_paths[:MAX_LIST_ITEMS])

    def _generation_note(self, explanation: ArchitectureExplanation) -> str:
        confidence = round(explanation.confidence * 100)
        return (
            "This document was generated from repository summary, dependency graph, "
            f"call graph, and parser evidence with {confidence}% confidence."
        )

    def _markdown(
        self,
        title: str,
        sections: tuple[ArchitectureDocSection, ...],
    ) -> str:
        body = "\n\n".join(
            f"## {section.heading}\n\n{section.content.strip()}" for section in sections
        )
        return f"# {title}\n\n{body}\n"
