from dataclasses import dataclass
from pathlib import Path

from backend.app.services.repository_summary import (
    RepositorySummary,
    RepositorySummaryError,
    RepositorySummaryService,
)

MAX_LIST_ITEMS = 8


class ReadmeGeneratorError(Exception):
    """Raised when README generation cannot continue."""


@dataclass(frozen=True)
class ReadmeSection:
    """One generated README section."""

    heading: str
    content: str


@dataclass(frozen=True)
class ReadmeStats:
    """Measurable output statistics for generated README content."""

    section_count: int
    word_count: int
    language_count: int
    key_file_count: int
    key_symbol_count: int


@dataclass(frozen=True)
class GeneratedReadme:
    """Repository README generated from indexed code intelligence."""

    repository_path: str
    title: str
    markdown: str
    sections: tuple[ReadmeSection, ...]
    evidence_paths: tuple[str, ...]
    stats: ReadmeStats


class ReadmeGeneratorService:
    """Generates a grounded README from repository summary facts."""

    def __init__(self, summary_service: RepositorySummaryService) -> None:
        self.summary_service = summary_service

    def generate(self, repository_path: Path) -> GeneratedReadme:
        """Generate README Markdown for a repository path."""
        try:
            summary = self.summary_service.summarize(repository_path)
        except RepositorySummaryError as error:
            raise ReadmeGeneratorError(str(error)) from error

        root = Path(summary.repository_path)
        title = root.name or "Repository"
        sections = (
            ReadmeSection("Overview", summary.overview),
            ReadmeSection("Repository Stats", self._stats_section(summary)),
            ReadmeSection("Languages", self._languages_section(summary)),
            ReadmeSection("Key Files", self._key_files_section(summary)),
            ReadmeSection("Notable Symbols", self._symbols_section(summary)),
            ReadmeSection("Architecture Signals", self._architecture_section(summary)),
            ReadmeSection("Getting Started", self._getting_started_section(root)),
            ReadmeSection("Generated By CodeInsight", self._generation_note(summary)),
        )
        markdown = self._markdown(title, sections)
        return GeneratedReadme(
            repository_path=summary.repository_path,
            title=title,
            markdown=markdown,
            sections=sections,
            evidence_paths=summary.evidence_paths,
            stats=ReadmeStats(
                section_count=len(sections),
                word_count=len(markdown.split()),
                language_count=len(summary.languages),
                key_file_count=len(summary.key_files),
                key_symbol_count=len(summary.key_symbols),
            ),
        )

    def _stats_section(self, summary: RepositorySummary) -> str:
        stats = summary.stats
        return "\n".join(
            [
                f"- Files: {stats.file_count}",
                f"- Directories: {stats.directory_count}",
                f"- Parsed source files: {stats.parsed_file_count}",
                f"- Parsed symbols: {stats.symbol_count}",
                f"- Internal dependencies: {stats.dependency_count}",
                f"- Call sites: {stats.call_count}",
                f"- Indexed embeddings: {stats.indexed_embedding_count}",
            ]
        )

    def _languages_section(self, summary: RepositorySummary) -> str:
        if not summary.languages:
            return "No source languages were detected by the repository scanner."
        return "\n".join(
            f"- {item.language}: {item.file_count} files, {item.size_bytes} bytes"
            for item in summary.languages[:MAX_LIST_ITEMS]
        )

    def _key_files_section(self, summary: RepositorySummary) -> str:
        if not summary.key_files:
            return "No key source files were identified."
        return "\n".join(
            "- "
            f"`{item.path}`"
            f" ({item.language or 'unknown'}, {item.symbol_count} symbols, "
            f"{item.dependency_count} outgoing dependencies, "
            f"{item.dependent_count} incoming dependencies)"
            for item in summary.key_files[:MAX_LIST_ITEMS]
        )

    def _symbols_section(self, summary: RepositorySummary) -> str:
        if not summary.key_symbols:
            return "No source symbols were extracted."
        return "\n".join(
            "- "
            f"`{item.name}` ({item.kind}) in `{item.path}`:{item.line}"
            + (f", parent `{item.parent}`" if item.parent else "")
            for item in summary.key_symbols[:MAX_LIST_ITEMS]
        )

    def _architecture_section(self, summary: RepositorySummary) -> str:
        signals = list(summary.dependency_highlights) + list(summary.call_highlights)
        if summary.embedding_indexed:
            signals.append("Semantic embeddings are indexed for repository-aware retrieval.")
        if not signals:
            return "No dependency, call graph, or embedding signals were available."
        return "\n".join(f"- {signal}" for signal in signals[:MAX_LIST_ITEMS])

    def _getting_started_section(self, root: Path) -> str:
        commands = self._setup_commands(root)
        if not commands:
            return (
                "Review the key files above, then follow the project-specific setup "
                "instructions in the repository."
            )
        return "\n".join(
            ["Detected setup entry points:"] + [f"- `{command}`" for command in commands]
        )

    def _setup_commands(self, root: Path) -> tuple[str, ...]:
        candidates = [
            ("package.json", "npm install"),
            ("pyproject.toml", "python -m pip install -e ."),
            ("requirements.txt", "python -m pip install -r requirements.txt"),
            ("go.mod", "go test ./..."),
            ("Cargo.toml", "cargo test"),
            ("pom.xml", "mvn test"),
            ("build.gradle", "gradle test"),
            ("Makefile", "make"),
        ]
        return tuple(command for filename, command in candidates if (root / filename).exists())

    def _generation_note(self, summary: RepositorySummary) -> str:
        return (
            "This README was generated from repository scan, parser, dependency graph, "
            "call graph, and embedding metadata collected by CodeInsight."
        )

    def _markdown(self, title: str, sections: tuple[ReadmeSection, ...]) -> str:
        body = "\n\n".join(
            f"## {section.heading}\n\n{section.content.strip()}" for section in sections
        )
        return f"# {title}\n\n{body}\n"
